# Generated by Django 2.2.6 on 2019-10-08 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBLearn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='summary',
            field=models.TextField(default='this is cool'),
        ),
    ]
