# Generated by Django 2.2.6 on 2019-10-09 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBLearn', '0008_auto_20191009_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.TextField(),
        ),
    ]
